external: # Manually registered ops which are not in `native_functions.yaml`
  var_mean.correction:
    kernel: manually registered
    structuted: manually registered
    cpp_namespace: manually registered
  native_group_norm:
    kernel: manually registered
    structuted: manually registered
    cpp_namespace: manually registered
  native_group_norm_backward:
    kernel: manually registered
    structuted: manually registered
    cpp_namespace: manually registered
details: # The details of the MPS ops.
  cumsum.out:
    starting_macOS_version: 13.0
  var_mean.correction:
    included_in_latest: True
  native_group_norm:
    included_in_latest: True
  native_group_norm_backward:
    included_in_latest: True